### ISSUE TITLE
Signing builds

### ISSUE THREAD

**Issue by Jay031** [joeireland/electron-circleci#1]
Hi, I have a .p12 and certificate for windows in my repo, how can I sign both builds?

I just used your config and it helped me a lot.
On Mac Build I get: keychain to create: Exited with code 255
But I guess I just have to rename my .p12 file?

Thanks in advance! Love your effort!

**Comment by cdaringe** [comment]
any forward motion here?

**Comment by joeireland** [comment]
You should never store a .p12 into your GITHUB repo for security reasons. Hackers can obtain your .p12 file and work toward cracking it to obtain your valuable secrets. The solution to that is to put your secrets into Circle CI so that hackers cannot get their hands on them.
